### ISSUE TITLE
Column 'licenseid' cannot be null after accepting the order

### ISSUE THREAD

**Issue by Th3St0ni3** [ConanDoyl/tekbase-whmcs#4]
**Describe the bug**
Every time a customer (in my case a test customer) books a license via the system, I get the following error message as soon as I release the order.

Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'licenseid' cannot be null (SQL: insert into `mod_tekbase_licenses` (`serviceid`, `customerid`, `licenseid`, `licensekey`, `siteip`, `siteurl`, `sitepath`, `version`, `cms`, `shop`, `gwislots`, `rwislots`, `swislots`, `updated_at`, `created_at`) values (31, MeMpbFwD3e8q, ?, Not retrieved yet.
To retrieve the License Key make sure you've set url and path at the settings!, , domain/tekbase/, /var/www/vhosts/domain/httpdocs/tekbase/, private, ?, ?, 1, 1, 1, 2022-02-10 13:35:27, 2022-02-10 13:35:27))

domain is replaced with the correct values in the original error message and is only entered here for anonymization.

I hope you can help me to solve the problem.

**To Reproduce**
1. Create an order as an customer
2. As Admin, try to accept the order. As soon as you try it the error is displayed

**Versions:**
 - WHMCS: 8.4.0
 - tekbase-whmcs: latets downloadable version

**Logs:**

10.02.2022 13:35 {"StatusCode":"500","Message":"Server replied with an error."}

10.02.2022 13:35 Module Create Failed - [Service ID: 31](https://whmcsdomain/admin/clientsservices.php?id=31) - Error: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'licenseid' cannot be null (SQL: insert into `mod_tekbase_licenses` (`serviceid`, `customerid`, `licenseid`, `licensekey`, `siteip`, `siteurl`, `sitepath`, `version`, `cms`, `shop`, `gwislots`, `rwislots`, `swislots`, `updated_at`, `created_at`) values (31, MeMpbFwD3e8q, ?, <b><font color='#FF000'>Not retrieved yet.</font></b><br/>To retrieve the License Key make sure you've set url and path at the settings!, , domain/tekbase/, /var/www/vhosts/domain/httpdocs/tekbase/, private, ?, ?, 1, 1, 1, 2022-02-10 13:35:27, 2022-02-10 13:35:27))

**Comment by ConanDoyl** [comment]
Thanks, i'll check that.

**Comment by ConanDoyl** [comment]
Has been fixed in the new Release =)
